name: Zip Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release sf_street_cleaning
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ‚§µÔ∏è Check out code from GitHub
        uses: actions/checkout@v4

      - name: üì¶ Create zipped release package
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/sf_street_cleaning"
          zip sf_street_cleaning.zip -r ./

      - name: ‚¨ÜÔ∏è Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/sf_street_cleaning/sf_street_cleaning.zip
